# Generated by Django 4.2 on 2024-07-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('city_name', models.CharField(max_length=100)),
                ('search_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
