# Generated by Django 4.2 on 2024-07-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citysearch',
            name='search_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
