# Generated by Django 4.2 on 2024-07-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_citysearch_search_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citysearch',
            name='city_name',
            field=models.CharField(max_length=255),
        ),
    ]
